export default {
  FISH: {
    '24995': {
      _id: 24995,
      previousWeatherSet: [7],
      weatherSet: [1],
      startHour: 5.5,
      endHour: 6.5,
      locations: [181],
      bait: 20675,
      bestCatchPath: [20675],
      predators: {},
      patch: 4.5,
      folklore: 2505,
      collectable: false,
      fishEyes: false,
      snagging: null,
      hookset: 'Precision',
      tug: 'heavy',
      gig: null,
      aquarium: { water: 'freshwater', size: 1 },
      dataMissing: null,
    },
    '28925': {
      _id: 28925,
      previousWeatherSet: [1, 2],
      weatherSet: [3, 4],
      startHour: 16,
      endHour: 24,
      locations: [206],
      bait: 27589,
      bestCatchPath: [27589],
      predators: {},
      patch: 5.2,
      folklore: 2507,
      collectable: false,
      fishEyes: false,
      snagging: null,
      hookset: 'Powerful',
      tug: 'heavy',
      gig: null,
      aquarium: null,
      dataMissing: null,
    },
    '27515': {
      _id: 27515,
      previousWeatherSet: [],
      weatherSet: [],
      startHour: 0,
      endHour: 24,
      locations: [236],
      bait: 27588,
      bestCatchPath: [27588],
      predators: {},
      patch: 5.0,
      folklore: null,
      collectable: true,
      fishEyes: false,
      snagging: null,
      hookset: 'Powerful',
      tug: 'medium',
      gig: null,
      aquarium: null,
      dataMissing: null,
    },
    // fix garland missing 4899 in 69
    '4899': {
      _id: 4899,
      previousWeatherSet: [],
      weatherSet: [],
      startHour: 0,
      endHour: 24,
      predators: {},
      fishEyes: false,
      snagging: false,
      hookset: null,
      tug: 'medium',
      dataMissing: true,
      anglerFishId: 85,
      bait: 2619,
      locations: [69, 74],
      bestCatchPath: [2619],
      patch: 2,
    },
    '4911': {
      startHour: 17,
      endHour: 22,
    },
    '4921': {
      weatherSet: [2, 1, 3, 4, 5],
    },
    '4985': {
      startHour: 17,
      endHour: 10,
    },
    '4999': {
      weatherSet: [1, 2, 3, 4],
    },
    '7702': {
      weatherSet: [7, 8],
      startHour: 17,
      endHour: 7,
    },
    '7902': {
      startHour: 17,
      endHour: 18.5,
      endHourText: '18:30',
    },
    '7903': {
      weatherSet: [3, 4, 5],
      startHour: 3,
      endHour: 5,
    },
    '7905': {
      weatherSet: [3, 4],
      startHour: 17,
      endHour: 19.5,
      endHourText: '19:30',
    },
    '7906': {
      startHour: 17.5,
      endHour: 18,
      startHourText: '17:30',
    },
    '7918': {
      weatherSet: [1],
      startHour: 17.5,
      endHour: 20,
      startHourText: '17:30',
    },
    '7921': {
      weatherSet: [2, 1],
      startHour: 21.5,
      endHour: 3,
      startHourText: '21:30',
    },
    '7923': {
      weatherSet: [4],
      startHour: 23,
      endHour: 4,
    },
    '7927': {
      startHour: 16,
      endHour: 18.75,
      endHourText: '18:45',
    },
    '7933': {
      startHour: 22,
      endHour: 4,
    },
    '7937': {
      weatherSet: [7],
      startHour: 19.5,
      endHour: 2.75,
      startHourText: '19:30',
      endHourText: '2:45',
    },
    '7947': {
      weatherSet: [4],
      startHour: 4.5,
      endHour: 10,
      startHourText: '4:30',
    },
    '7948': {
      startHour: 23.5,
      endHour: 1.0833333333333333,
      startHourText: '23:30',
      endHourText: '1:05',
    },
    '8756': {
      previousWeatherSet: [2, 1],
      weatherSet: [3, 4, 5],
      startHour: 20,
      endHour: 4,
    },
    '8757': {
      previousWeatherSet: [],
      weatherSet: [2, 1],
      startHour: 19,
      endHour: 2,
    },
    '8767': {
      previousWeatherSet: [2, 1],
      weatherSet: [4],
      startHour: 0,
      endHour: 3.3333333333333335,
      endHourText: '3:20',
    },
    '8776': {
      previousWeatherSet: [2, 1],
      weatherSet: [4],
      startHour: 4.5,
      endHour: 11.5,
      startHourText: '4:30',
      endHourText: '11:30',
    },
    '12786': {
      startHour: 18,
      endHour: 6,
    },
    '12796': {
      startHour: 8,
      endHour: 18,
    },
    '12802': {
      startHour: 18,
      endHour: 20.5,
      endHourText: '20:30',
    },
    '12803': {
      weatherSet: [3],
      startHour: 18,
      endHour: 3,
    },
    '12828': {
      startHour: 22,
      endHour: 3.3333333333333335,
      endHourText: '3:20',
    },
    '12832': {
      weatherSet: [2, 1],
      startHour: 9,
      endHour: 17,
    },
    '13728': {
      weatherSet: [16],
      startHour: 0,
      endHour: 4,
      bait: 4937,
      bestCatchPath: [2599, 4937],
    },
    '13731': {
      weatherSet: [2, 1],
      startHour: 15.5,
      endHour: 17,
      startHourText: '15:30',
    },
    '13732': {
      weatherSet: [3, 4],
      startHour: 0,
      endHour: 6,
    },
    '14218': {
      weatherSet: [9],
      startHour: 18,
      endHour: 24,
    },
    '15638': {
      weatherSet: [3],
      startHour: 21,
      endHour: 2,
    },
    '16746': {
      weatherSet: [16],
      startHour: 10,
      endHour: 18,
    },
    '20034': {
      weatherSet: [1],
      startHour: 10,
      endHour: 18,
    },
    '20085': {
      startHour: 16,
      endHour: 18.25,
      endHourText: '18:15',
    },
    '20124': {
      startHour: 17,
      endHour: 10,
    },
    '20524': {
      startHour: 8,
      endHour: 16,
    },
    // fix 黄昏珊瑚
    '12795': {
      tug: 'light',
    },
    // fix 云水母
    '5038': {
      tug: 'light',
    },
    '8769': {
      bait: 4937,
      bestCatchPath: [12711, 4937],
    },
    '7945': {
      weatherSet: [2, 1],
      startHour: 20,
      endHour: 4,
      bait: 4937,
      bestCatchPath: [12704, 4937],
    },
    '7911': {
      bait: 4948,
      bestCatchPath: [2594, 4948],
    },
    '7946': {
      bait: 4937,
      bestCatchPath: [12711, 4937],
    },
    '16745': {
      bait: 12724,
      bestCatchPath: [12712, 12716, 12724],
    },
    '4893': {
      tug: 'medium',
    },
    '30492': {
      tug: 'light',
    },
    '24888': {
      previousWeatherSet: [],
    },
    '12750': {
      tug: 'medium',
    },
    '12808': {
      hookset: 'Precision',
      tug: 'light',
    },
    '12772': {
      snagging: true,
    },
    '20073': {
      weatherSet: [3, 4, 5, 11],
    },
    '20021': {
      bait: 20675,
      bestCatchPath: [20675],
    },
    '20060': {
      bait: 20614,
      bestCatchPath: [20614],
    },
    '27412': {
      snagging: false,
    },
    '12745': {
      tug: 'medium',
    },
    '4912': {
      tug: 'medium',
    },
    '12734': {
      tug: 'light',
    },
    '20048': {
      tug: 'medium',
    },
    '4977': {
      bait: 2600,
      bestCatchPath: [2600],
    },
    '5043': {
      bestCatchPath: [2600, 4977],
    },
    '23073': {
      _id: 23073,
      previousWeatherSet: [],
      weatherSet: [],
      startHour: 0,
      endHour: 24,
      predators: {},
      fishEyes: false,
      snagging: false,
      hookset: 'Powerful',
      tug: 'medium',
      dataMissing: false,
      anglerFishId: 776,
      bait: 12704,
      locations: [116],
      bestCatchPath: [12704],
      patch: 4.3,
    },
    '23075': {
      _id: 23075,
      previousWeatherSet: [],
      weatherSet: [],
      startHour: 0,
      endHour: 24,
      predators: {},
      fishEyes: false,
      snagging: false,
      hookset: 'Powerful',
      tug: 'medium',
      dataMissing: false,
      anglerFishId: 778,
      bait: 28634,
      locations: [131],
      bestCatchPath: [28634],
      patch: 4.3,
    },
    '17565': {
      patch: 4.3,
      bait: 28634,
      hookset: 'Precision',
      bestCatchPath: [28634],
    },
    '12817': {
      hookset: 'Powerful',
      tug: 'heavy',
    },
    '4997': {
      _id: 4997,
      hookset: 'Powerful',
    },
    '12771': {
      _id: 12771,
      hookset: 'Precision',
      tug: 'light',
    },
    '17564': {
      _id: 17564,
      patch: 3.5,
      hookset: 'Precision',
      tug: 'light',
    },
    // '12776': {
    //   bestCatchPathGroup: {
    //     '140': {
    //       bestCatchPath: [12710],
    //     },
    //     '141': {
    //       bestCatchPath: [12710],
    //     },
    //     '142': {
    //       bestCatchPath: [30136],
    //     },
    //     '146': {
    //       bestCatchPath: [30136],
    //     },
    //   },
    // },
    '12815': {
      bestCatchPath: [30136, 12776],
    },
    '12816': {
      bestCatchPath: [30136, 12776],
    },
    '12827': {
      bestCatchPath: [30136, 12776],
    },
    '16744': {
      bestCatchPath: [30136, 12776],
    },
    '17589': {
      bestCatchPath: [30136, 12776],
    },
  },
  OCEAN_FISHING_FISH: {
    '28937': {
      _id: 28937,
      name_chs: '加拉迪翁虾虎',
      icon: 29003,
      tug: 'light',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 7,
      points: 10,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '28938': {
      _id: 28938,
      name_chs: '加拉迪翁鳀鱼',
      icon: 29034,
      tug: 'light',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 9,
      points: 11,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '28939': {
      _id: 28939,
      name_chs: '玫瑰鲷鱼',
      icon: 29009,
      tug: 'light',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 14,
      points: 34,
      doubleHook: [3, 4],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '28940': {
      _id: 28940,
      name_chs: '三角刺鱼',
      icon: 29152,
      tug: 'light',
      hookset: null,
      biteTimeMin: 10,
      biteTimeMax: 23,
      points: 43,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [3, 4],
      time: 0,
      locations: [241],
    },
    '28941': {
      _id: 28941,
      name_chs: '阳光蝴蝶鱼',
      icon: 29016,
      tug: 'light',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 8,
      points: 10,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '28942': {
      _id: 28942,
      name_chs: '暗淡鲨',
      icon: 29011,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 16,
      biteTimeMax: 30,
      points: 34,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [8],
      time: 0,
      locations: [237],
    },
    '29718': {
      _id: 29718,
      name_chs: '海投刀',
      icon: 29042,
      tug: 'light',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 13,
      points: 27,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [16],
      time: 0,
      locations: [241],
    },
    '29719': {
      _id: 29719,
      name_chs: '碧玉头',
      icon: 29043,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 10,
      biteTimeMax: 23,
      points: 40,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [3, 4],
      time: 0,
      locations: [237],
    },
    '29720': {
      _id: 29720,
      name_chs: '梅尔托尔龙虾',
      icon: 29013,
      tug: 'light',
      hookset: null,
      biteTimeMin: 17,
      biteTimeMax: 27,
      points: 45,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29721': {
      _id: 29721,
      name_chs: '天堂鱼',
      icon: 29033,
      tug: 'light',
      hookset: null,
      biteTimeMin: 16,
      biteTimeMax: 20,
      points: 50,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '29722': {
      _id: 29722,
      name_chs: '尸鬼梭鱼',
      icon: 29035,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 6,
      points: 10,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [5, 6],
      time: 0,
      locations: [239],
    },
    '29723': {
      _id: 29723,
      name_chs: '猎豹鳗',
      icon: 29126,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 15,
      points: 14,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [7, 8],
      time: 0,
      locations: [237],
    },
    '29724': {
      _id: 29724,
      name_chs: '海中爆弹',
      icon: 29046,
      tug: 'light',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 8,
      points: 27,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [6],
      time: 0,
      locations: [239],
    },
    '29725': {
      _id: 29725,
      name_chs: '莫莫拉·莫拉',
      icon: 29021,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 14,
      biteTimeMax: 20,
      points: 22,
      doubleHook: [2],
      bait: 29716,
      baitExtra: 29722,
      bestCatchPath: [29715, 29722],
      bestCatchPathExtra: [29716],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '29726': {
      _id: 29726,
      name_chs: '梅尔托尔蝴蝶鱼',
      icon: 29167,
      tug: 'light',
      hookset: null,
      biteTimeMin: 17,
      biteTimeMax: 27,
      points: 51,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '29727': {
      _id: 29727,
      name_chs: '步兵剑',
      icon: 29022,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 13,
      points: 49,
      doubleHook: [2],
      bait: 29722,
      baitExtra: null,
      bestCatchPath: [29715, 29722],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '29728': {
      _id: 29728,
      name_chs: '罗塔诺梭子鰆',
      icon: 29025,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 10,
      points: 13,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [14],
      time: 0,
      locations: [243],
    },
    '29729': {
      _id: 29729,
      name_chs: '罗塔诺沙丁鱼',
      icon: 29004,
      tug: 'light',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 10,
      points: 10,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29730': {
      _id: 29730,
      name_chs: '深海平鱼',
      icon: 29048,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 12,
      points: 15,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [11, 14],
      time: 0,
      locations: [243],
    },
    '29731': {
      _id: 29731,
      name_chs: '深红钓鮟鱇',
      icon: 29049,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 14,
      points: 32,
      doubleHook: [4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29732': {
      _id: 29732,
      name_chs: '灯鱼',
      icon: 29516,
      tug: 'light',
      hookset: null,
      biteTimeMin: 11,
      biteTimeMax: 16,
      points: 47,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29733': {
      _id: 29733,
      name_chs: '魔鳗',
      icon: 29045,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 8,
      biteTimeMax: 15,
      points: 38,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [3, 4],
      time: 0,
      locations: [243],
    },
    '29734': {
      _id: 29734,
      name_chs: '青色章鱼',
      icon: 29051,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 17,
      biteTimeMax: 27,
      points: 59,
      doubleHook: [4],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 13,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '29735': {
      _id: 29735,
      name_chs: '铬铁锤头鲨',
      icon: 29026,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 15,
      biteTimeMax: 28,
      points: 32,
      doubleHook: [4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29736': {
      _id: 29736,
      name_chs: '浮冰鱼',
      icon: 29310,
      tug: 'light',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 7,
      points: 13,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [15, 16],
      time: 0,
      locations: [241],
    },
    '29737': {
      _id: 29737,
      name_chs: '巨乌贼',
      icon: 29027,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 10,
      points: 11,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29738': {
      _id: 29738,
      name_chs: '放浪神之石',
      icon: 29100,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 12,
      biteTimeMax: 24,
      points: 11,
      doubleHook: [2],
      bait: 29716,
      baitExtra: 29718,
      bestCatchPath: [29714, 29718],
      bestCatchPathExtra: [29716],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29739': {
      _id: 29739,
      name_chs: '拉诺西亚水母',
      icon: 29755,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 4,
      points: 10,
      doubleHook: [3, 4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 15,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '29740': {
      _id: 29740,
      name_chs: '蓬松海龙',
      icon: 29053,
      tug: 'light',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 20,
      points: 35,
      doubleHook: [4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 16,
      fishTipType: null,
      notAvailableWeatherSet: [3, 4],
      time: 0,
      locations: [239],
    },
    '29741': {
      _id: 29741,
      name_chs: '蜘蛛蟹',
      icon: 29111,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 21,
      points: 36,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29742': {
      _id: 29742,
      name_chs: '暗鹦鹉螺',
      icon: 29811,
      tug: 'light',
      hookset: null,
      biteTimeMin: 17,
      biteTimeMax: 24,
      points: 46,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29743': {
      _id: 29743,
      name_chs: '古老恐鱼',
      icon: 29019,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 16,
      points: 52,
      doubleHook: [2],
      bait: 29718,
      baitExtra: null,
      bestCatchPath: [29714, 29718],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29744': {
      _id: 29744,
      name_chs: '醉鱼',
      icon: 29373,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 16,
      biteTimeMax: 27,
      points: 253,
      doubleHook: [1],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: {
        '28938': 3,
      },
      bonus: 0,
      fishTipType: 2,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [237],
    },
    '29745': {
      _id: 29745,
      name_chs: '小利维亚桑',
      icon: 29147,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 16,
      biteTimeMax: 27,
      points: 204,
      doubleHook: [1],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: {
        '29727': 1,
      },
      bonus: 0,
      fishTipType: 2,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [239],
    },
    '29746': {
      _id: 29746,
      name_chs: '海铠靴',
      icon: 29077,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 11,
      biteTimeMax: 18,
      points: 204,
      doubleHook: [1],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: {
        '29731': 2,
      },
      bonus: 0,
      fishTipType: 2,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [243],
    },
    '29747': {
      _id: 29747,
      name_chs: '海流星',
      icon: 29157,
      tug: 'heavy',
      hookset: 'Precision',
      biteTimeMin: 16,
      biteTimeMax: 27,
      points: 226,
      doubleHook: [1],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: {
        '29743': 1,
      },
      bonus: 0,
      fishTipType: 2,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [241],
    },
    '29748': {
      _id: 29748,
      name_chs: '锤爪龙虾',
      icon: 29082,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 69,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [242],
    },
    '29749': {
      _id: 29749,
      name_chs: '天堂之钥',
      icon: 29069,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 67,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [238],
    },
    '29750': {
      _id: 29750,
      name_chs: '幽灵鲨',
      icon: 29065,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 4,
      points: 78,
      doubleHook: [4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [238],
    },
    '29751': {
      _id: 29751,
      name_chs: '流银刃',
      icon: 29759,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 6,
      points: 213,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [238],
    },
    '29752': {
      _id: 29752,
      name_chs: '海神印',
      icon: 29073,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 4,
      points: 71,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [238],
    },
    '29753': {
      _id: 29753,
      name_chs: '钉牡蛎',
      icon: 29067,
      tug: 'light',
      hookset: null,
      biteTimeMin: 8,
      biteTimeMax: 9,
      points: 222,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [238],
    },
    '29754': {
      _id: 29754,
      name_chs: '巨食鮟鱇',
      icon: 29070,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 7,
      points: 78,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [238],
    },
    '29755': {
      _id: 29755,
      name_chs: '秘银君',
      icon: 29078,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 5,
      points: 196,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [240],
    },
    '29756': {
      _id: 29756,
      name_chs: '灵敏舞者',
      icon: 28001,
      tug: 'light',
      hookset: null,
      biteTimeMin: 11,
      biteTimeMax: 15,
      points: 444,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [238],
    },
    '29757': {
      _id: 29757,
      name_chs: '海荨麻',
      icon: 29434,
      tug: 'light',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 8,
      points: 156,
      doubleHook: [4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 15,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [240],
    },
    '29758': {
      _id: 29758,
      name_chs: '巨大枪鱼',
      icon: 29095,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: null,
      points: 127,
      doubleHook: [2],
      bait: 29761,
      baitExtra: null,
      bestCatchPath: [29716, 29761],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [240],
    },
    '29759': {
      _id: 29759,
      name_chs: '海难船帆',
      icon: 29084,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 59,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [240],
    },
    '29760': {
      _id: 29760,
      name_chs: '太阳神面纱',
      icon: 29161,
      tug: 'light',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 5,
      points: 69,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [240],
    },
    '29761': {
      _id: 29761,
      name_chs: '高级以太药虱',
      icon: 29089,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 4,
      points: 65,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [240],
    },
    '29762': {
      _id: 29762,
      name_chs: '浮游碟鱼',
      icon: 29661,
      tug: 'light',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 10,
      points: 222,
      doubleHook: [4],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 15,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [244],
    },
    '29763': {
      _id: 29763,
      name_chs: '以太海龙',
      icon: 29074,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 245,
      doubleHook: [2],
      bait: 29761,
      baitExtra: null,
      bestCatchPath: [29716, 29761],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 16,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [240],
    },
    '29764': {
      _id: 29764,
      name_chs: '珊瑚海龙',
      icon: 29155,
      tug: 'light',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 10,
      points: 189,
      doubleHook: [4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 16,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [242],
    },
    '29765': {
      _id: 29765,
      name_chs: '无赖龙',
      icon: 28002,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 4,
      points: 345,
      doubleHook: [2],
      bait: 29761,
      baitExtra: null,
      bestCatchPath: [29716, 29761],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [240],
    },
    '29766': {
      _id: 29766,
      name_chs: '人鱼发',
      icon: 29072,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 94,
      doubleHook: [4],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 13,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [238],
    },
    '29767': {
      _id: 29767,
      name_chs: '清道夫',
      icon: 29085,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 6,
      points: 216,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [244],
    },
    '29768': {
      _id: 29768,
      name_chs: '沉寂者',
      icon: 29156,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 6,
      points: 89,
      doubleHook: [4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [244],
    },
    '29769': {
      _id: 29769,
      name_chs: '深海鳗',
      icon: 29088,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 8,
      points: 81,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [244],
    },
    '29770': {
      _id: 29770,
      name_chs: '处刑者',
      icon: 29092,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 8,
      points: 216,
      doubleHook: [4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [244],
    },
    '29771': {
      _id: 29771,
      name_chs: '狂野海胆',
      icon: 29813,
      tug: 'light',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 6,
      points: 79,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [242],
    },
    '29772': {
      _id: 29772,
      name_chs: '尖吻鲈',
      icon: 29546,
      tug: 'light',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 6,
      points: 95,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [244],
    },
    '29773': {
      _id: 29773,
      name_chs: '幻纱披风',
      icon: 29374,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 5,
      biteTimeMax: 7,
      points: 198,
      doubleHook: [4],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 13,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [242],
    },
    '29774': {
      _id: 29774,
      name_chs: '蜗牛鱼',
      icon: 28003,
      tug: 'light',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 5,
      points: 246,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [244],
    },
    '29775': {
      _id: 29775,
      name_chs: '阿龙纳斯',
      icon: 29816,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 95,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [244],
    },
    '29776': {
      _id: 29776,
      name_chs: '尾骨鱼',
      icon: 29093,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 79,
      doubleHook: [2],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [242],
    },
    '29777': {
      _id: 29777,
      name_chs: '剪碎手巴塞洛缪',
      icon: 29075,
      tug: 'light',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 5,
      points: 221,
      doubleHook: [4],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [242],
    },
    '29778': {
      _id: 29778,
      name_chs: '巡游者',
      icon: 29066,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 5,
      points: 79,
      doubleHook: [2],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [242],
    },
    '29779': {
      _id: 29779,
      name_chs: '寄生幸存者',
      icon: 29086,
      tug: 'light',
      hookset: null,
      biteTimeMin: 2,
      biteTimeMax: 4,
      points: 69,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [240],
    },
    '29780': {
      _id: 29780,
      name_chs: '浪子鱼',
      icon: 29331,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 3,
      biteTimeMax: 8,
      points: 95,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [244],
    },
    '29781': {
      _id: 29781,
      name_chs: '守领鳍龙',
      icon: 29162,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 4,
      biteTimeMax: 7,
      points: 79,
      doubleHook: [3, 4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 0,
      locations: [242],
    },
    '29782': {
      _id: 29782,
      name_chs: '漏斗鲨',
      icon: 29731,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 6,
      biteTimeMax: 10,
      points: 213,
      doubleHook: [4],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 14,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [238],
    },
    '29783': {
      _id: 29783,
      name_chs: '坠天鱼',
      icon: 28004,
      tug: 'medium',
      hookset: null,
      biteTimeMin: 7,
      biteTimeMax: 8,
      points: 374,
      doubleHook: [2],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: null,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [242],
    },
    '29784': {
      _id: 29784,
      name_chs: '幻光巨齿鲨',
      icon: 28005,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 20,
      biteTimeMax: 35,
      points: 100,
      doubleHook: [1],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: 1,
      notAvailableWeatherSet: [1],
      time: 0,
      locations: [237],
    },
    '29785': {
      _id: 29785,
      name_chs: '幻光盘丽鱼',
      icon: 28006,
      tug: 'heavy',
      hookset: 'Precision',
      biteTimeMin: 20,
      biteTimeMax: 35,
      points: 100,
      doubleHook: [1],
      bait: 29715,
      baitExtra: null,
      bestCatchPath: [29715],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: 1,
      notAvailableWeatherSet: [1],
      time: 0,
      locations: [239],
    },
    '29786': {
      _id: 29786,
      name_chs: '幻光海马',
      icon: 28007,
      tug: 'heavy',
      hookset: 'Precision',
      biteTimeMin: 20,
      biteTimeMax: 35,
      points: 100,
      doubleHook: [1],
      bait: 29714,
      baitExtra: null,
      bestCatchPath: [29714],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: 1,
      notAvailableWeatherSet: [1],
      time: 0,
      locations: [241],
    },
    '29787': {
      _id: 29787,
      name_chs: '幻光鲈',
      icon: 28008,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 21,
      biteTimeMax: 35,
      points: 100,
      doubleHook: [1],
      bait: 29716,
      baitExtra: null,
      bestCatchPath: [29716],
      bestCatchPathExtra: [],
      predators: null,
      bonus: 0,
      fishTipType: 1,
      notAvailableWeatherSet: [1],
      time: 0,
      locations: [243],
    },
    '29788': {
      _id: 29788,
      name_chs: '索蒂斯',
      icon: 28009,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 11,
      points: 500,
      doubleHook: [1],
      bait: 2603,
      baitExtra: null,
      bestCatchPath: [2603],
      bestCatchPathExtra: [],
      predators: {
        '29749': 2,
        '29752': 1,
      },
      bonus: 0,
      fishTipType: 3,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [238],
    },
    '29789': {
      _id: 29789,
      name_chs: '珊瑚蝠鲼',
      icon: 28010,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 9,
      biteTimeMax: 10,
      points: 500,
      doubleHook: [1],
      bait: 2613,
      baitExtra: null,
      bestCatchPath: [2613],
      bestCatchPathExtra: [],
      predators: {
        '29758': 2,
      },
      bonus: 0,
      fishTipType: 3,
      notAvailableWeatherSet: [],
      time: 3,
      locations: [240],
    },
    '29790': {
      _id: 29790,
      name_chs: '石骨鱼',
      icon: 28011,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 10,
      biteTimeMax: 12,
      points: 500,
      doubleHook: [1],
      bait: 2591,
      baitExtra: null,
      bestCatchPath: [2591],
      bestCatchPathExtra: [],
      predators: {
        '29768': 1,
        '29769': 1,
      },
      bonus: 0,
      fishTipType: 3,
      notAvailableWeatherSet: [],
      time: 2,
      locations: [244],
    },
    '29791': {
      _id: 29791,
      name_chs: '依拉丝莫龙',
      icon: 28012,
      tug: 'heavy',
      hookset: null,
      biteTimeMin: 10,
      biteTimeMax: 11,
      points: 500,
      doubleHook: [1],
      bait: 2619,
      baitExtra: null,
      bestCatchPath: [2619],
      bestCatchPathExtra: [],
      predators: {
        '29781': 3,
      },
      bonus: 0,
      fishTipType: 3,
      notAvailableWeatherSet: [],
      time: 1,
      locations: [242],
    },
  },
  OCEAN_FISHING_BONUS: {
    '0': {
      _id: 0,
      objective: null,
      requirement: null,
      icon: 0,
      order: 0,
    },
    '1': {
      _id: 1,
      objective: '千鱼祝福',
      requirement: '达成条件：获得的渔分超过2500。',
      icon: 65901,
      order: 1,
    },
    '2': {
      _id: 2,
      objective: '万鱼贺喜',
      requirement: '达成条件：获得的渔分超过5000。',
      icon: 65902,
      order: 2,
    },
    '3': {
      _id: 3,
      objective: '珍鱼',
      requirement: '达成条件：钓到一条★★★★鱼。',
      icon: 65903,
      order: 3,
    },
    '4': {
      _id: 4,
      objective: '传说鱼',
      requirement: '达成条件：钓到一条★★★★★鱼。',
      icon: 65904,
      order: 4,
    },
    '5': {
      _id: 5,
      objective: '瞬钓',
      requirement: '达成条件：在幻海流中钓到15条鱼。',
      icon: 65905,
      order: 5,
    },
    '6': {
      _id: 6,
      objective: '爆钓王',
      requirement: '达成条件：在幻海流中钓到35条鱼。',
      icon: 65906,
      order: 6,
    },
    '7': {
      _id: 7,
      objective: '丰渔：加拉迪翁湾',
      requirement: '达成条件：小队全体在加拉迪翁湾合计钓到10种以上的鱼类。',
      icon: 65907,
      order: 7,
    },
    '8': {
      _id: 8,
      objective: '丰渔：梅尔托尔海峡南',
      requirement: '达成条件：小队全体在梅尔托尔海峡南合计钓到10种以上的鱼类。',
      icon: 65908,
      order: 8,
    },
    '9': {
      _id: 9,
      objective: '丰渔：梅尔托尔海峡北',
      requirement: '达成条件：小队全体在梅尔托尔海峡北合计钓到10种以上的鱼类。',
      icon: 65909,
      order: 9,
    },
    '10': {
      _id: 10,
      objective: '丰渔：罗塔诺海',
      requirement: '达成条件：小队全体在罗塔诺海合计钓到10种以上的鱼类。',
      icon: 65910,
      order: 10,
    },
    '11': {
      _id: 11,
      objective: '传说中的大渔旗',
      requirement: '达成条件：小队全体合计钓到3条以上★★★★★的鱼。',
      icon: 65911,
      order: 11,
    },
    '12': {
      _id: 12,
      objective: '利姆莱茵的宠爱之子',
      requirement: '达成条件：由自己引发幻海流。',
      icon: 65912,
      order: 12,
    },
    '13': {
      _id: 13,
      objective: '八爪旅人',
      requirement: '达成条件：小队全体合计钓到150只以上的章鱼类。',
      icon: 65913,
      order: 13,
    },
    '14': {
      _id: 14,
      objective: '捕鲨人',
      requirement: '达成条件：小队全体合计钓到200条以上的鲨鱼类。',
      icon: 65914,
      order: 14,
    },
    '15': {
      _id: 15,
      objective: '水母狂魔',
      requirement: '达成条件：小队全体合计钓到150只以上的水母类。',
      icon: 65915,
      order: 15,
    },
    '16': {
      _id: 16,
      objective: '龙马惊神',
      requirement: '达成条件：小队全体合计钓到100只以上的海龙或海马。',
      icon: 65916,
      order: 16,
    },
  },
  OCEAN_FISHING_WEATHER: {
    '1': {
      _id: 1,
      icon: 60201,
      name_chs: '碧空',
    },
    '2': {
      _id: 2,
      icon: 60202,
      name_chs: '晴朗',
    },
    '3': {
      _id: 3,
      icon: 60203,
      name_chs: '阴云',
    },
    '4': {
      _id: 4,
      icon: 60204,
      name_chs: '薄雾',
    },
    '5': {
      _id: 5,
      icon: 60205,
      name_chs: '微风',
    },
    '6': {
      _id: 6,
      icon: 60206,
      name_chs: '强风',
    },
    '7': {
      _id: 7,
      icon: 60207,
      name_chs: '小雨',
    },
    '8': {
      _id: 8,
      icon: 60208,
      name_chs: '暴雨',
    },
    '9': {
      _id: 9,
      icon: 60209,
      name_chs: '打雷',
    },
    '10': {
      _id: 10,
      icon: 60210,
      name_chs: '雷雨',
    },
    '11': {
      _id: 11,
      icon: 60211,
      name_chs: '扬沙',
    },
    '14': {
      _id: 14,
      icon: 60214,
      name_chs: '热浪',
    },
    '15': {
      _id: 15,
      icon: 60215,
      name_chs: '小雪',
    },
    '16': {
      _id: 16,
      icon: 60216,
      name_chs: '暴雪',
    },
  },
  OCEAN_FISHING_TIPS: {
    tip1: {
      title: '[苍海龙骑]海钓手册',
      link: 'https://ngabbs.com/read.php?tid=20553241',
      author: '月咏泠音@摩杜纳',
    },
  },
  STARLIGHT_CELEBRATION: {
    startTime: 1608616800000,
    endTime: 1609912800000,
    weather: 15,
    spots: [35, 36, 104, 90, 91, 81, 100, 105, 106, 197, 198],
    territories: [129, 128, 133, 132, 339, 340, 341, 641],
    fish: [4905, 7713, 7919, 7923, 7917, 7701],
  },
}
