export default [
  {
    status: {
      effects: [1465, 895, 1730, 1729, 1353, 47, 1173, 1166, 761, 805],
      isFishing: true,
      baitId: 29717,
      spotId: 60,
      mooch: false,
      prevFishId: -1,
    },
    currentRecord: {
      startTime: Date.now(),
      fishId: -1,
      hq: false,
      size: 0,
      snagging: true,
      chum: false,
      fishEyes: false,
      surfaceScale: false,
      identicalCast: false,
      baitId: 29717,
      mooch: false,
      spotId: 60,
    },
    records: [
      {
        startTime: 1605630916412,
        biteTime: 1605630930636,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 49,
        snagging: true,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 29717,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605630941866,
        biteTime: 1605630961652,
        hookset: 'normal',
        fishId: 4885,
        hq: false,
        size: 332,
        snagging: true,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 29717,
        mooch: false,
        spotId: 60,
        tug: 'medium',
      },
      {
        startTime: 1605630979469,
        biteTime: 1605631003512,
        fishId: -1,
        hq: false,
        size: 0,
        snagging: true,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 29717,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
    ],
    readableRecords: [
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '01:48',
        biteInterval: 14.2,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: true,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 29717,
        baitText: '万能拟饵',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        fishId: 4885,
        fishText: '蓝章鱼',
        et: '01:57',
        biteInterval: 19.8,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: true,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 29717,
        baitText: '万能拟饵',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        fishId: -1,
        fishText: '',
        et: '02:10',
        biteInterval: 24,
        tug: 'light',
        tugText: '轻杆',
        hookset: '',
        hq: false,
        snagging: true,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 29717,
        baitText: '万能拟饵',
      },
    ],
  },
  {
    status: {
      effects: [1465, 895, 1730, 1729, 1353, 47, 1173, 1166, 761, 805],
      isFishing: true,
      baitId: 2585,
      spotId: 60,
      mooch: false,
      prevFishId: 7684,
    },
    currentRecord: { fishId: -1, hq: false, size: 0 },
    records: [
      {
        startTime: 1605717976776,
        biteTime: 1605717990573,
        hookset: 'normal',
        fishId: 4869,
        hq: true,
        size: 92,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605718000269,
        biteTime: 1605718015951,
        hookset: 'normal',
        fishId: 4904,
        hq: false,
        size: 331,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4869,
        mooch: true,
        spotId: 60,
        tug: 'medium',
      },
      {
        startTime: 1605718038934,
        biteTime: 1605718069863,
        hookset: 'normal',
        fishId: 7684,
        hq: false,
        size: 1341,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4904,
        mooch: true,
        spotId: 60,
        tug: 'heavy',
      },
    ],
    readableRecords: [
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        prevWeatherId: 2,
        prevWeatherText: '碧空',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '19:17',
        biteInterval: 13.8,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: true,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        prevWeatherId: 2,
        prevWeatherText: '碧空',
        fishId: 4904,
        fishText: '梭子鰆',
        et: '19:25',
        biteInterval: 15.7,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4869,
        baitText: '梅尔托尔虾虎',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 1,
        weatherText: '碧空',
        prevWeatherId: 2,
        prevWeatherText: '碧空',
        fishId: 7684,
        fishText: '拾荒鮟鱇',
        et: '19:39',
        biteInterval: 30.9,
        tug: 'heavy',
        tugText: '',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4904,
        baitText: '梭子鰆',
      },
    ],
  },
  {
    status: {
      effects: [1465, 895, 1730, 1729, 1353, 47, 1173, 1166, 761, 805],
      isFishing: true,
      baitId: 2585,
      spotId: 60,
      mooch: false,
      prevFishId: 4912,
    },
    currentRecord: { fishId: -1, hq: false, size: 0, startTime: Date.now() },
    records: [
      {
        startTime: 1605805932907,
        biteTime: 1605805948675,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 59,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605805962353,
        biteTime: 1605805977107,
        hookset: 'normal',
        fishId: 4904,
        hq: false,
        size: 245,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4869,
        mooch: true,
        spotId: 60,
        tug: 'medium',
      },
      {
        startTime: 1605805992430,
        biteTime: 1605806008111,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 53,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605806022282,
        biteTime: 1605806032690,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 69,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605806062109,
        biteTime: 1605806074838,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 50,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605807203059,
        biteTime: 1605807219698,
        hookset: 'normal',
        fishId: 4869,
        hq: false,
        size: 83,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605807232091,
        biteTime: 1605807247435,
        hookset: 'normal',
        fishId: 4904,
        hq: false,
        size: 368,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4869,
        mooch: true,
        spotId: 60,
        tug: 'medium',
      },
      {
        startTime: 1605807948662,
        biteTime: 1605807963970,
        hookset: 'normal',
        fishId: 4869,
        hq: true,
        size: 93,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 2585,
        mooch: false,
        spotId: 60,
        tug: 'light',
      },
      {
        startTime: 1605807979247,
        biteTime: 1605807990930,
        hookset: 'normal',
        fishId: 4904,
        hq: false,
        size: 320,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4869,
        mooch: true,
        spotId: 60,
        tug: 'medium',
      },
      {
        startTime: 1605808002671,
        biteTime: 1605808022499,
        hookset: 'normal',
        fishId: 4912,
        hq: false,
        size: 893,
        snagging: false,
        chum: false,
        fishEyes: false,
        surfaceScale: false,
        identicalCast: false,
        baitId: 4904,
        mooch: true,
        spotId: 60,
        tug: 'medium',
      },
    ],
    readableRecords: [
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 3,
        weatherText: '阴云',
        prevWeatherId: 3,
        prevWeatherText: '阴云',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '17:54',
        biteInterval: 15.8,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 3,
        weatherText: '阴云',
        prevWeatherId: 3,
        prevWeatherText: '阴云',
        fishId: 4904,
        fishText: '梭子鰆',
        et: '18:04',
        biteInterval: 14.8,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4869,
        baitText: '梅尔托尔虾虎',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 3,
        weatherText: '阴云',
        prevWeatherId: 3,
        prevWeatherText: '阴云',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '18:14',
        biteInterval: 15.7,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 3,
        weatherText: '阴云',
        prevWeatherId: 3,
        prevWeatherText: '阴云',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '18:24',
        biteInterval: 10.4,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 3,
        weatherText: '阴云',
        prevWeatherId: 3,
        prevWeatherText: '阴云',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '18:38',
        biteInterval: 12.7,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 2,
        weatherText: '晴朗',
        prevWeatherId: 3,
        prevWeatherText: '晴朗',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '01:09',
        biteInterval: 16.6,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 2,
        weatherText: '晴朗',
        prevWeatherId: 3,
        prevWeatherText: '晴朗',
        fishId: 4904,
        fishText: '梭子鰆',
        et: '01:19',
        biteInterval: 15.3,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4869,
        baitText: '梅尔托尔虾虎',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 2,
        weatherText: '晴朗',
        prevWeatherId: 3,
        prevWeatherText: '晴朗',
        fishId: 4869,
        fishText: '梅尔托尔虾虎',
        et: '05:25',
        biteInterval: 15.3,
        tug: 'light',
        tugText: '轻杆',
        hookset: '普通',
        hq: true,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 2585,
        baitText: '沙蚕',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 2,
        weatherText: '晴朗',
        prevWeatherId: 3,
        prevWeatherText: '晴朗',
        fishId: 4904,
        fishText: '梭子鰆',
        et: '05:35',
        biteInterval: 11.7,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4869,
        baitText: '梅尔托尔虾虎',
      },
      {
        spotId: 60,
        spotText: '骷髅谷沿岸地',
        weatherId: 2,
        weatherText: '晴朗',
        prevWeatherId: 3,
        prevWeatherText: '晴朗',
        fishId: 4912,
        fishText: '拟鮟鱇',
        et: '05:43',
        biteInterval: 19.8,
        tug: 'medium',
        tugText: '中杆',
        hookset: '普通',
        hq: false,
        snagging: false,
        chum: false,
        surfaceScale: false,
        surfaceScaleFishText: '',
        identicalCast: false,
        identicalCastText: '',
        fishEyes: false,
        baitId: 4904,
        baitText: '梭子鰆',
      },
    ],
  },
]
