name: Tencent COS Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build website
        run: |
          npm install
          npm run build
      - name: Tencent Update COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: dist
          remote_path: /
          clean: true
      - name: Post Deploy Event For Static Web Apps Workflows
        uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.STATIC_WEB_APPS_WORKFLOW_TRIGGER_TOKEN }}
            repository: ricecake404/ffxiv-pastry-fish-list
            event-type: start-deploy-static-web-apps

